ViewModels/OwnerViewModel.cs
using PracticalTraining.Models;
using System.Web;
using System.Collections.Generic;

namespace PracticalTraining.ViewModels
{
    public class OwnerViewModel
    {
        public Dictionary<string, string> Management = new Dictionary<string, string>();
        public Dictionary<string, string> Documentation = new Dictionary<string, string>();

        public OwnerViewModel()
        {
            Management =  new Dictionary<string, string> { { "Персонал", "StaffInfoes" }, { "Помещения", "PlaceInfoes" }, { "Услуги", "ServiceInfoes" }, 
                                                              { "Способы оплаты", "PaymentInfoes" }, { "О фотостудии", "BaseInfoes"}, { "Управление паролями",  "UserInfoes"} };
            Documentation = new Dictionary<string, string> { { "Отчет о посещаемости помещений", "DownloadPlaceReport"}, 
                                                             { "Отчет о потоке клиентов", "DownloadClientReport" }, 
                                                             { "Табель учета рабочего времени", "DownloadTimeReport" }, 
                                                             { "Табель расчета оплаты труда", "DownloadPayReport" }};

        }


    }
}

Controllers/OwnerController.cs
using Microsoft.AspNetCore.Mvc;
using PracticalTraining.Models;
using PracticalTraining.Models.DatabaseMANKA;
using PracticalTraining.ViewModels;
using Microsoft.AspNetCore.Http;
using Documentation;
using System.IO;

namespace PracticalTraining.Controllers
{
    public class OwnerController: Controller
    {
        private MANKADocumentation doc;

        public OwnerController() { }

        public IActionResult Index()
        {
            UserInfoList.CreateList();
            return View(new OwnerViewModel());
        }

        public FileResult DownloadPlaceReport()
        {
            doc = new MANKADocumentation();
            return Download(doc.BuildDocumentОтчетОПосещаемостиПомещений());
        }

        public FileResult DownloadClientReport()
        {
            doc = new MANKADocumentation();
            return Download(doc.BuildDocumentОтчетОПотокеКлиентов());
        }

        public FileResult DownloadTimeReport()
        {
            doc = new MANKADocumentation();
            return Download(doc.BuildDocumentТабельУчетаРабочегоВремени());
        }

        public FileResult DownloadPayReport()
        {
            doc = new MANKADocumentation();
            return Download(doc.BuildDocumentТабельРасчетаОплатыТруда());
        }

        public FileResult Download(string path)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

Views/Owner/Index.cshtml
@model OwnerViewModel

@section menu
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Owner" asp-action="Index">На главную</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Выйти</a>
    </li>
}

<body>
    
    <div class="row">
        <div class="col-md-6">
            <h2>Управление</h2>
            @foreach(string key in Model.Management.Keys)
            {
                @Html.ActionLink(key, "Index", Model.Management[key])
                <br/>
            }
        </div>
        <div class="col-md-4">
            <h2>Отчетность</h2>
            @foreach(string key in Model.Documentation.Keys)
            {
                @Html.ActionLink(key, Model.Documentation[key], "Owner");<br/>
            }
        </div>
    </div>    
</body>